### ISSUE TITLE
old releases removed

### ISSUE THREAD

**Issue by cklm** [yaroslavche/BitMask#23]
Hi @yaroslavche, 

thanks for this package! We saw, that you had removed the old releases. We have a project depending on version 0.2.0. It cannot be upgraded to version 1.0.0, because the minimum php-version changed. Is there a specific reason that you removed the old releases (like a bug, a security-concern, ...)?

Thanks in advance!

**Comment by yaroslavche** [comment]
Hi, @cklm
in general, not many changes compared to current release. Mostly - migrating to PHP7.4 and just one important: [wrong initialization of the map](https://github.com/yaroslavche/BitMask/issues/18).
Sorry that I've broken your dependencies, let me check what I can do (maybe I have that tags or branches locally). Honestly, I even didn't expect that someone use this in production =)

**Comment by yaroslavche** [comment]
I've created release from tag. Please check if it's working fine now. And if yes, then keep in mind about wrong initialization (to avoid issues, need explicitly set all keys to false before using). If you're using AssociativeBitmask

**Comment by cklm** [comment]
That works, just switched to the new release. Thank you very much for the fast help!
